# Currently doesn't work - need to fix. Fire up postgres via docker run command for now.
version: '3.8'

services:
  postgres:
    container_name: communipute-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securePassword
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: